In [1]:
import numpy as np

ЗАДАЧА 1

Объявление матриц

In [2]:
matrixA = np.array([[1, 2, 1], [-2, 1, 1]])
matrixA

array([[ 1,  2,  1],
       [-2,  1,  1]])

In [3]:
matrixB = np.array([[3,1], [-1,0], [2,4]])
matrixB

array([[ 3,  1],
       [-1,  0],
       [ 2,  4]])

In [4]:
matrixC = np.array([[-2,1], [1,-1], [1,2]])
matrixC

array([[-2,  1],
       [ 1, -1],
       [ 1,  2]])

Приведение матрицы А в размерност 3х2

Транспонирование

In [6]:
matrixA_Transpose = matrixA.transpose()
matrixA_Transpose

array([[ 1, -2],
       [ 2,  1],
       [ 1,  1]])

Через reshape

In [8]:
matrixA_Reshape = matrixA.reshape(3,2)
matrixA_Reshape

array([[ 1,  2],
       [ 1, -2],
       [ 1,  1]])

Вычисления, согласно требований задачи

In [9]:
matrixA_Transpose+2*matrixB

array([[7, 0],
       [0, 1],
       [5, 9]])

In [10]:
matrixA_Reshape+2*matrixB

array([[ 7,  4],
       [-1, -2],
       [ 5,  9]])

In [11]:
matrixB+2*matrixC

array([[-1,  3],
       [ 1, -2],
       [ 4,  8]])

ЗАДАЧА 2

Нулевая матрица

In [74]:
matrix0 = np.zeros((8, 8), dtype='int')
matrix0

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

Заполнение 1

In [75]:
matrix0[1::2, 0::2] = 1
matrix0[0::2, 1::2] = 1
matrix0

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

ЗАДАЧА 3

In [18]:
vector1=np.arange(start=0, stop=1.5, step=0.1, dtype=float)
vector1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4])

In [20]:
vector2=np.arange(start=1, stop=7, step=1, dtype=float)
vector2

array([1., 2., 3., 4., 5., 6.])

In [21]:
matrix1 = vector1.reshape(5,3)
matrix1

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8],
       [0.9, 1. , 1.1],
       [1.2, 1.3, 1.4]])

In [23]:
matrix2 = vector2.reshape(3,2)
matrix2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [24]:
np.dot(matrix1, matrix2)

array([[ 1.3,  1.6],
       [ 4. ,  5.2],
       [ 6.7,  8.8],
       [ 9.4, 12.4],
       [12.1, 16. ]])

ЗАДАЧА 4

In [27]:
vector3 = np.arange(start=1, stop=37, step=1, dtype=int)
vector3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [43]:
vector4 = []
for i in range(len(vector3)):
    if(vector3[i]%3 == 0):
        vector4.append(vector3[i])
vector4 = np.array(vector4)
vector4

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])